### ISSUE TITLE
Ambigous Error in Swift 1.2

### ISSUE THREAD

**Issue by banxi1988** [SwiftyJSON/Alamofire-SwiftyJSON#14]
在 Swift 1.2中下面两个方法的签名是等价的:

``` Swift
   public func responseSwiftyJSON(completionHandler: (NSURLRequest, NSHTTPURLResponse?, JSON, NSError?) -> Void) -> Self 
// VS
    public func responseSwiftyJSON(queue: dispatch_queue_t? = nil, options: NSJSONReadingOptions = .AllowFragments, completionHandler: (NSURLRequest, NSHTTPURLResponse?, JSON, NSError?) -> Void) -> Self 

```

**Comment by jdoes** [comment]
I have the same problem @banxi1988 , You found a solution?

**Comment by mdziadkowiec** [comment]
I changed the name of the second function to: responseSwiftyJSONWithQueue and it is working now.

It seems that Swift 1.2 no longer support the same functions names (and return types) with diffrerent parameters types.

Check this out: https://developer.apple.com/swift/blog/?id=20
(Section: Redefinition or Overload?)

**Comment by wongzigii** [comment]
Closing for inactive.
