### ISSUE TITLE
Push to cocoapods

### ISSUE THREAD

**Issue by erkie** [SwiftyJSON/Alamofire-SwiftyJSON#15]
I see there is a podspec file but `Alamofire-SwiftyJSON` is not a available on cocoapods.org. It seems to be possible to have swift dependencies on cocoapods using cocoapods `0.36.0`.

Could you push it?

**Comment by cellularmitosis** [comment]
+1

**Comment by marcus30** [comment]
+1

**Comment by alec-c4** [comment]
+1

**Comment by ippy04** [comment]
+1

**Comment by nickkjordan** [comment]
until then:
`pod 'Alamofire-SwiftyJSON', :git => "https://github.com/SwiftyJSON/Alamofire-SwiftyJSON.git"`

**Comment by minhoryang** [comment]
+1

**Comment by cheebow** [comment]
+1

**Comment by sambecker** [comment]
+1

**Comment by sambecker** [comment]
@nickkjordan I tried that solution and running `pod install` did successfully add `Alamofire-SwiftyJSON` to my Xcode project, however, I cannot import the class or use the `.responseSwiftyJSON` extension. Have you had similar issues?

**Comment by nickkjordan** [comment]
@sambecker I was able to import using `import Alamofire_SwiftyJSON`

**Comment by josafafilho** [comment]
+1

**Comment by hemincong** [comment]
Dependcency is not allowed from podspecs  http://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of 

Could you push it?

**Comment by jk** [comment]
+1

@tangplin Can we help you to push your work to CocoaPods? I would like to help.

**Comment by blerchy** [comment]
+1

**Comment by kostiakoval** [comment]
`pod 'Alamofire-SwiftyJSON'` doesn't contains Alamofire and SwiftyJSON as dependencies :(

`s.dependency 'Alamofire'`
`s.dependency 'SwiftyJSON'`

**Comment by gabovanlugo** [comment]
+1

**Comment by pcoulter** [comment]
+1

**Comment by erkie** [comment]
Was this fixed with https://github.com/SwiftyJSON/Alamofire-SwiftyJSON/pull/28?

**Comment by nickkjordan** [comment]
@erkie No

**Comment by jett0423** [comment]
+1

**Comment by wongzigii** [comment]
Closing for inactive.
