### ISSUE TITLE
Ambiguous use of 'responseSwiftyJSON'

### ISSUE THREAD

**Issue by valzevul** [SwiftyJSON/Alamofire-SwiftyJSON#21]
Hello,

after installing Xcode 6.3 the following code

```
Alamofire .request(.POST, url, parameters: data) .responseSwiftyJSON { (_, _, json, error) in
    if (error != nil) {
        println("Error with registration: \(error?.localizedDescription)")
     } else {
        println("Success!")
    }
}
```

produces the problem "Ambiguous use of 'responseSwiftyJSON'".

**Comment by firedog7881** [comment]
I am getting this as well. I can tell it is because there are two functions with the same name '.responseSwiftJSON' but I can't figure out how to fix this, I'm still too new to Swift and programming in general.

**Comment by hdoria** [comment]
+1

**Comment by regularex** [comment]
Looks like the compiler might be having an issue distinguishing the overloaded functions. Just rename one of them. Worked great.

**Comment by firedog7881** [comment]
Which one did you rename? Which one are you using that doesn't change the functionality?

**Comment by regularex** [comment]
Give the the dispatch queue a name like responseAsyncHandler and rename the return function the same in the other.

**Comment by firedog7881** [comment]
Ahhh, So when we call responseSwiftyJSON in our programming we are calling the first one which then calls the second one? I think I got it now. Sorry, only about two months into programming and swift. Thanks for the help.

**Comment by jccf091** [comment]
This make the compiler happy.
    Alamofire.request(.GET, "url")
      .responseSwiftyJSON({(request, response, json, error) in
        println(json)
        println(error)
    })

**Comment by Aymenworks** [comment]
@jccf091 +1
You know why ?

**Comment by ylisr** [comment]
@regularex You are absolutely right! Almost missed your comment.
For someone who is still confused, here is what I did: search for `responseSwiftyJSON` in my project, find the function:

    public func responseSwiftyJSON(completionHandler: (NSURLRequest, NSHTTPURLResponse?,JSON, NSError?) -> Void) -> Self {
        return responseSwiftyJSON(queue:nil, options:NSJSONReadingOptions.AllowFragments, completionHandler:completionHandler)
    }
and change the function name to `responseSwiftyJSONRenamed`, as well as places where I use it. You can tell which one you are using by the parameters you pass in.

**Comment by explosion78** [comment]
Because the second function has the default values. Comment out the first function (without queue and options) worked out for me.

**Comment by kishikawakatsumi** [comment]
To resolve this problem, without using trailing closure syntax, enclose the last closure in parentheses.
Like below:

```swift
Alamofire.request(.POST, url, parameters: data).responseSwiftyJSON({ (_, _, json, error) in
    if (error != nil) {
        println("Error with registration: \(error?.localizedDescription)")
    } else {
        println("Success!")
    }
})
```

**Comment by dbleicher** [comment]
@kishikawakatsumi  -- works like a champ.  Thanks!

**Comment by kukabi** [comment]
@kishikawakatsumi works for me, thanks..

**Comment by x140yu** [comment]
@kishikawakatsumi thanks!

**Comment by kostiakoval** [comment]
It would be nice to rename the method. I love trailing closure syntax (as everyone else)

**Comment by tapz** [comment]
I always get the following error. I tried to rename the second function and comment the first one out. Also tried to add the parameter types and return type to the closure. Didn't help.

"Cannot invoke 'responseSwiftyJSON' with an argument list of type '((_, _, _, _) -> _)'"

        Alamofire.request(...)
            .responseSwiftyJSON { (request, response, json, error) in
                if (error != nil) {
                    println("Error with registration: \(error?.localizedDescription)")
                } else {
                    println("Success!")
                }
            }

**Comment by kostiakoval** [comment]
@tapz As @kishikawakatsumi  suggested, 
> "Don't use trailing closure syntax"

In your code you are still using trailing closures syntax 
```
.responseSwiftyJSON { (request, response, json, error) in ...
}
```
vs 
```
.responseSwiftyJSON({ (_, _, json, error) in ...
)
```

**Comment by tapz** [comment]
It does not help if I don't use the trailing closure.

**Comment by allaire** [comment]
Why using paranthesis with Alamofire-swiftyJSON works:

```swift
        Alamofire.request(.GET, "http://httpbin.org/get")
            .responseSwiftyJSON({ (_, _, json, _) in
                println(json)
        })
```

**Comment by damianesteban** [comment]
Does anyone have this actually working properly?

**Comment by wongzigii** [comment]
Closing for inactive.
