### ISSUE TITLE
Please update from Swift 2.0

### ISSUE THREAD

**Issue by losh11** [SwiftyJSON/Alamofire-SwiftyJSON#25]

**Comment by petershaw** [comment]
And pls update *to* Swift 2.0, too

**Comment by albertkim** [comment]
Waiting for this one. The current build doesn't fit the new response/error handling conventions in Alamofire.

**Comment by kimdv** [comment]
Any status on this one ? @tangplin ?

**Comment by kostiakoval** [comment]
It's now support 2.0. This issue can be closed

**Comment by losh11** [comment]
Confirmed as working fine and great!

**Comment by kostiakoval** [comment]
Great!
