### ISSUE TITLE
Adapt to Alamofire 1.3.0

### ISSUE THREAD

**Issue by kukudas** [SwiftyJSON/Alamofire-SwiftyJSON#26]
The parameter name for serializer from the response function has change to responseSerializer.

**Comment by thomasdegry** [comment]
See PR https://github.com/SwiftyJSON/Alamofire-SwiftyJSON/pull/27
Unsure if this should be merged in straight to master though.

**Comment by kostiakoval** [comment]
This issue should be closed. It was fixed and Alamofire 1.3.0 is old.
The latest version of Alamofire is 3.0

**Comment by wongzigii** [comment]
Alamofire 4.0 + Swift 3.0 has launched. 🎉🎉🎉
