### ISSUE TITLE
Compile time issue

### ISSUE THREAD

**Issue by BiancaMinnaar** [SwiftyJSON/Alamofire-SwiftyJSON#31]
Hi,

I am getting an error on line 40 with missing parameter for completionHandler.
Subsequent errors follow after correction.

Please review with xcode 7.6 beta and Alamofire 1.3.1 on deployment target 8.4

Regards,

Brian Minnaar

**Comment by noder123** [comment]
Bump. Issue with Swift 2.0 XCode 7 and Alamofire 3

**Comment by wongzigii** [comment]
Closing for inactive.
@BiancaMinnaar @noder123 Hey, the Swift 3 and Alamofire 4 version has launched. Feel free to open an new issue.
