### ISSUE TITLE
Forcing Alamofire 1.3 which isn't compatible with Swift 2.0

### ISSUE THREAD

**Issue by pdutourgeerling** [SwiftyJSON/Alamofire-SwiftyJSON#33]
The current version is forcing Alamofire 1.3 which doesn't support Swift 2.0. Can you remove the dependencies in Alamofire-SwiftyJSON.podspec so this will work with Swift 2.0?

In the meantime I created a workaround available at https://github.com/pdutourgeerling/Alamofire-SwiftyJSON-Podspec.
It doesn't force any version of any framework so it's working with Swift 2.0.

**Comment by kostiakoval** [comment]
You shouldn't use a framework in podscpec to specify customer frameworks. Instead you should use `vendored_frameworks`
https://guides.cocoapods.org/syntax/podspec.html#vendored_frameworks

**Comment by wongzigii** [comment]
Closing for inactive.
