### ISSUE TITLE
Cannot install Alamofire-SwiftyJSON

### ISSUE THREAD

**Issue by aizcheryz** [SwiftyJSON/Alamofire-SwiftyJSON#34]
i can't install using pod 'Alamofire-SwiftyJSON'
and if i use manually, unsupport for Swift 2.0
how to fix it? thanks

**Comment by pdutourgeerling** [comment]
Look here: https://github.com/pdutourgeerling/Alamofire-SwiftyJSON-Podspec

**Comment by fraserscottmorrison** [comment]
This should be added to the main ReadMe file

**Comment by wongzigii** [comment]
This should now works. Closing.
