### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by xkiRox** [SwiftyJSON/Alamofire-SwiftyJSON#4]
![captura de pantalla 2014-11-01 a las 5 52 43 p m](https://cloud.githubusercontent.com/assets/5804556/4873567/0d9ec518-621a-11e4-9fab-7e19b04a0e00.png)

I have tried to use the library but when I try I get Error .responseSwiftyJSON place, also I have a warring not as removed. 
Can you help me?

**Comment by kostiakoval** [comment]
Could you confirm that this is still a valid error? I think it's closed
