### ISSUE TITLE
Cannot call value of non-function type NSHTTPURLResponse

### ISSUE THREAD

**Issue by EduardJS** [SwiftyJSON/Alamofire-SwiftyJSON#40]
Hello ! I have installed Alamofire 3.0 and SwiftyJSON 2.3 via CocoaPods and then I have just brough Alamofire-SwiftyJSON manually in my XCode project. 

When I try building it I get an error on line 40 in Alamofire-SwiftyJSON.swift yelling at me like the following:

`Cannot call value of non-function type NSHTTPURLResponse`

Any idea how to fix this ?

**Comment by benjaminhorner** [comment]
Same problem here

**Comment by hiragram** [comment]
@benjaminhorner ↑ Isn't this merged to original repository?

**Comment by jregnauld** [comment]
Not yet unfortunately :(

**Comment by benjaminhorner** [comment]
@hiragram not yet :(

**Comment by hiragram** [comment]
That is too bad I'm sorry :(
