### ISSUE TITLE
Unable to find a specification for `Alamofire-SwiftyJSON`

### ISSUE THREAD

**Issue by danipralea** [SwiftyJSON/Alamofire-SwiftyJSON#43]
I got this when trying to update my Podfile with `pod 'Alamofire-SwiftyJSON'` in it

![screenshot 2016-01-12 23 29 26](https://cloud.githubusercontent.com/assets/768893/12277512/58d5d3e2-b984-11e5-87c3-3487fa574cdc.png)

**Comment by alanscarpa** [comment]
Give this a shot:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0.2'
pod 'SwiftyJSON'
pod 'Alamofire-SwiftyJSON', :podspec => 'https://raw.githubusercontent.com/pdutourgeerling/Alamofire-SwiftyJSON-Podspec/master/Alamofire-SwiftyJSON.podspec'
```

Found here: https://github.com/pdutourgeerling/Alamofire-SwiftyJSON-Podspec

**Comment by wongzigii** [comment]
@danipralea From the image you given, the ``` mark should be `'`.
