### ISSUE TITLE
Please update version to be compatible with Alamofire (~> 4.0)

### ISSUE THREAD

**Issue by RanaAbdou** [SwiftyJSON/Alamofire-SwiftyJSON#49]
- `Alamofire (~> 4.0)` required by `Podfile`
- `Alamofire (~> 4.0)` required by `AlamofireObjectMapper (4.0.0)`
- `Alamofire (~> 3.4)` required by `Alamofire-SwiftyJSON (0.1.1)`
- `Alamofire (~> 4.0)` required by `AlamofireImage (3.1.0)`

**Comment by wongzigii** [comment]
Alamofire 4.0 + Swift 3.0 has launched. 🎉🎉🎉
