### ISSUE TITLE
No such module "Alamofire" if I open the example project. 

### ISSUE THREAD

**Issue by samuelbeek** [SwiftyJSON/Alamofire-SwiftyJSON#5]
When I open the example project it says _no such module 'Alamofire'_. I've tried a few things (restarting Xcode, adding Alarmofire.swift) but can't fix it. 
![schermafbeelding 2014-11-05 om 08 31 45](https://cloud.githubusercontent.com/assets/248098/4914124/dcebccb2-64bd-11e4-9784-951abdad3bbd.png)

**Comment by tvich1** [comment]
Well there is no sure shot solution for this. Just try to clean your code again and again. If it doesn't works, make sure that your Xcode is of latest version.

Reference:-> [Fixing Alamofire No such module error](http://swiftforums.org/forum/alamofire/39-how-to-fix-alamofire-no-such-module-error#post39)

**Comment by mssiosteam** [comment]
I have clean 100 times

**Comment by wongzigii** [comment]
Closing for inactive.
