### ISSUE TITLE
Support for Carthage

### ISSUE THREAD

**Issue by perryprog** [SwiftyJSON/Alamofire-SwiftyJSON#57]
I'm not sure if there is support, but when I add to my `Cartfile` the line `github "SwiftyJSON/Alamofire-SwiftyJSON"`, I get the error:

```
*** Skipped building Alamofire-SwiftyJSON due to the error:
Dependency "Alamofire-SwiftyJSON" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/SwiftyJSON/Alamofire-SwiftyJSON/issues/new
```

**Comment by wongzigii** [comment]
@perryprog Carthage have already supported! You need to specific the release version likes:

    github "SwiftyJSON/Alamofire-SwiftyJSON" "master"

or 

    github "SwiftyJSON/Alamofire-SwiftyJSON" "2.0.0-beta.1"

**Comment by perryprog** [comment]
Oh. Duh.

Making PR to add this to the readme.
