### ISSUE TITLE
'JSON' is not convertible to 'JSON'

### ISSUE THREAD

**Issue by escv** [SwiftyJSON/Alamofire-SwiftyJSON#6]
I added the files of all the 3 Projects (alamofire, swiftyjson, alamofire-swiftyjson) to my project. When launching the app i get a compile error in:

/Users/ABCDEF/Documents/ios/Stream/Libraries/Alamofire-SwiftyJSON/Alamofire-SwiftyJSON.swift:51:47: 'JSON' is not convertible to 'JSON'

Does someone have any hints how to integrate the projects to a custom project?

Thanks in advance.
Greetings

**Comment by UNREALre** [comment]
So, guys, any progress here?
I use alamofire + swifty + haneke cache. That's my code

        Alamofire.request(.GET, self.matchListURL, parameters: nil)
            .responseSwiftyJSON { (req, res, myJSON, error) in
                    self.cache.set(value: myJSON, key: "myJSON")
                else {
                    //
                }
        }
And I get "JSON is not convertible to JSON". What's going on? Why?

**Comment by rainypixels** [comment]
I don't think this is a problem with SwiftyJSON, @dtJon, rather something weird about XCode's compiler error handling. In your particular situation, this should fix the problem:

```
var x: NSObject?
if (x == nil) {...}
```
Only an optional type can be checked for `nil` equality.

**Comment by codinggenie** [comment]
I had similar problem while using this code:
`jsonData["user"]["firstName"].string!`

I changed to this line:
`self.loginJson["user"]["email"].string as AnyObject!`

Now the error `inout JSON' is not convertible to 'JSON'` disappeared.
I have not tested the code for functionality, but the error seems to disappear and the code compiles.

**Comment by wongzigii** [comment]
Closing for inactive.
