### ISSUE TITLE
Unable to build using Xcode9

### ISSUE THREAD

**Issue by troyibm** [SwiftyJSON/Alamofire-SwiftyJSON#63]
I'm using carthage to pull in Alamofire-SwiftyJSON and when trying to build with Xcode 9 GM, I get the following build error:

*** Building scheme "AlamofireSwiftyJSON" in Alamofire-SwiftyJSON.xcodeproj
*** Building scheme "AWSCore" in AWSiOSSDKv2.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/troyibm/git/WPA4Auto-iPadApp-ios11/WPAAutoDemo/Carthage/Checkouts/aws-sdk-ios/AWSiOSSDKv2.xcodeproj -scheme AWSCore -configuration Release -derivedDataPath /Users/troyibm/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/aws-sdk-ios/40c7d5d60e0b80d70cd1502ef0cf8507f023f8d5 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/troyibm/git/WPA4Auto-iPadApp-ios11/WPAAutoDemo/Carthage/Checkouts/aws-sdk-ios)

I'm using the following in my Cartfile:

github "Alamofire/Alamofire" ~> 4.5
github "SwiftyJSON/SwiftyJSON"
github "SwiftyJSON/Alamofire-SwiftyJSON" "master"

**Comment by wongzigii** [comment]
3.0.0 is out! https://github.com/SwiftyJSON/Alamofire-SwiftyJSON/releases/tag/3.0.0
