### ISSUE TITLE
Getting wrong

### ISSUE THREAD

**Issue by AndorChen** [SwiftyJSON/Alamofire-SwiftyJSON#7]
New to Swift, but when followed the usage example in readme, still not get correct execution order:

``` swift
Alamofire.request(.GET, "http://httpbin.org/get", parameters: ["foo": "bar"])
            .responseSwiftyJSON { (request, response, json, error) in
    println("first")
}
println("second")
```

the `"second"` got printed before `"first"`.

Is there something I missed?

Thanks.

**Comment by wongzigii** [comment]
Closing for inactive.
