### ISSUE TITLE
The bundle contains disallowed nested bundles.

### ISSUE THREAD

**Issue by hlongvu** [SwiftyJSON/Alamofire-SwiftyJSON#70]
When submitting ios build with XCode 9.4, Swift 4.1.2 and Carthage I got this error:
Invalid Bundle. The bundle at 'MyApp.app/Frameworks/AlamofireSwiftyJSON.framework' contains disallowed nested bundles. An unknown error occurred.

**Comment by wongzigii** [comment]
Closing due to #72
