### ISSUE TITLE
Wrong PLIST entry in version 3.0.0

### ISSUE THREAD

**Issue by nubek** [SwiftyJSON/Alamofire-SwiftyJSON#71]
Inside the info.plist the `bundle version string` is still set to `2.0.0-beta.1` and not to `3.0.0`:

![screenshot01](https://user-images.githubusercontent.com/9840823/44724675-b10c6100-aad3-11e8-9100-6f52ada9ff0b.png)

This causes, that you get the following kind of error, when you try to upload an app with this framework to the App Store (or TestFlight):

![screenshot02](https://user-images.githubusercontent.com/9840823/44724701-c84b4e80-aad3-11e8-862d-a5a679f3c8df.png)

**Comment by wongzigii** [comment]
Closing due to #72
